#! /bin/bash

domain_array=($(aliyun cdn DescribeUserDomains | grep -i DomainName | cut -d ":" -f 2 | cut -d "," -f 1 | sed 's/\"//g' | sed 's/ //g'))
for i in ${!domain_array[@]}; do
   echo ${domain_array[$i]}
   aliyun cdn SetForceRedirectConfig --DomainName ${domain_array[$i]} --RedirectType "Https"
done
